# Generated by Django 5.0.2 on 2024-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_comment_pub_date_remove_comment_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
